
app_name: 'testModule'
project_name: 'testProject'
project_version: '0.1'

logging:
  level: DEBUG
  format: '%(levelname)s %(asctime)s  %(message)s'
  message_format: '%(project_name)s:%(project_version)s %(app_id)s %(_filename)s:%(_lineno)d [%(tags)s] '

  filters:
    trans:
      tag: 'TRANS:'   # tag 过滤
  handlers:
    - type: file
      enable: true
      filename: 'server.log'
      encoding: 'UTF-8'
      max_bytes: 67108864 # 64MB
      backup_count: 10

    - type: file
      enable: true
      filename: 'trans.log'   #运单日志跟踪
      encoding: 'UTF-8'
      max_bytes: 67108864 # 64MB
      backup_count: 10
      filter: 'trans'

    - type: console
      enable: true

http_trace: #自动日志记录
  level: DEBUG
  request:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true

  response:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true



datasources:
  - name: 'mongodb'
    class: 'mantis.fundamental.nosql.mongo.Datasource'
    host: '172.16.109.1'
    port: 27017
    dbname:
    user:
    password:
    enable: true

  - name: 'zk_1'
    type: 'zookeeper'
    enable: false
    hosts: 'localhost:2181'
    root: '/camel'

  - name: 'redis'
    class: 'mantis.fundamental.redis.datasource.Datasource'
    host: '172.16.109.1'
    port: 6379
    password: ''
    db: 0
    enable: true

message_brokers:
  - name: 'kafka_1'
    class: 'mantis.fundamental.kafka.MessageBroker'
    enable: false
    hosts: 'localhost:9092'
    zookeepers: 'localhost:2181'
    channels:
      - name: 'test'
        group: 'abcdef'  # simple_consumer if group is null
        handler:  'access.kafka.test.get_message' # last unit< get_message> is function object
        enable: true
        type: 'queue'

  - name: 'redis'
    class: 'mantis.fundamental.redis.broker.MessageBroker'
    host: '172.16.109.1'
    port: 6379
    password: ''
    db: 0
    enable: true
    channels:
      - name: 'ctp_contract_tick_queue'
#        handler: 'get_message'
        enable: true
        type: 'queue' # or queue

services:
  - name: 'http-subscribe'
    class: 'mantis.fundamental.flask.service.FlaskService'
    enable: true
    block: false
    cfgs:
      SQLALCHEMY_DATABASE_URI : 'sqlite:////tmp/test.db'
      SQLALCHEMY_BINDS:
      SQLALCHEMY_TRACK_MODIFICATIONS : true
      SQLALCHEMY_COMMIT_ON_TEARDOWN : true
      SECRET_KEY : "abc"
    http:
#      host : '172.16.109.237'
      host : '127.0.0.1'
      port : 0
      threaded: false
      debug: true

    blueprints:
      - package: 'http'
        url: '/v1'
        name: 'v1'
        register: true
        modules:
          - name: 'message'
            url: '/message'
            routes:
              - url: '/'                    # url name
                name: 'handle_message'   # function name
                methods: 'POST'

  - name:       'main'
    id:     'ctp-market-trader'
    enable:     true
    class:      'main.TradeAdapter'
    gateway:
      name: 'CTP'
      brokerID:   "9999"
      mdAddress:  "tcp://180.168.146.187:10011"  # real time
      tdAddress:  "tcp://180.168.146.187:10001"
#      mdAddress:  "tcp://180.168.146.187:10031" # 16:00 - 09:00
#      tdAddress:  "tcp://180.168.146.187:10030"
      userID:     "113967"
      password:  "loginmm6688"
      comments:  "交易服务器地址可以不设置,仅仅使用行情接收功能"
      authCode:   ''
      userProductInfo: ''

    init_channels: 'get,sub,pub,put'
    fanout:
      - name: 'switch0'
        channels:
#          - 'redis/future_ctp_ticks/queue'
          - 'redis/future_ctp_tick_{symbol}/pubsub'
      - name: 'logging'
        channels:
          - 'redis/trade.log.{service_type}/queue'
          - 'redis/trade.log.{service_type}.{service_id}/pubsub'

    ctp_tick_filters:
      - 'filters.CtpTickValidator'






# qpid-receive -b localhost:5672 -a "mq_test;{create:always,node:{type:queue,durable:true}}"






